<a href="https://colab.research.google.com/github/Narasimha0111/ml-ZoomCamp/blob/main/01-intro/01-intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print("Scikit-learn:", sklearn.__version__)

print("Environment ready!")

NumPy: 2.1.3
Pandas: 2.2.3
Scikit-learn: 1.6.1
Environment ready!


# 1.7 Introduction to NumPy


In [ ]:
import numpy as np

#Creating array


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10,3.5)

array([3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5])

# List to array

In [ ]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a[2]

np.int64(3)

In [ ]:
a[2]=10
a

array([ 1,  2, 10,  4,  5,  6])

Two more useful functions for creating arrays. arange creates a range of numbers - it works like the Python function range, except instead of an iterator it gives us a NumPy array. The last element is exclusive:

In [ ]:
np.arange(3,11)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

##Multi-dimensional arrays

In [ ]:
np.zeros((5,2)) #tuple shape , Uses mostly

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.zeros([5,2]) #list shape

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
n=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]]
         )

In [ ]:
n[0][1]

np.int64(2)

In [ ]:
n[0][1]=20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
n[2]

array([7, 8, 9])

In [ ]:
n[2]=[2,2,2]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 2,  2,  2]])

In [ ]:
n[:,2]

array([3, 6, 2])

In [ ]:
n[:,2]=[0,1,2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 2,  2,  2]])

#Randomly generated arrays

In [4]:
np.random.rand(5) #we get values between 0 and 1(Exclude) ->[0,1)

array([0.24099506, 0.53125125, 0.81471456, 0.24821365, 0.62297014])

In [5]:
np.random.rand(5,3)

array([[0.36186713, 0.21231714, 0.46021505],
       [0.54775483, 0.79222033, 0.81496083],
       [0.49815166, 0.6709095 , 0.91749306],
       [0.16719404, 0.85801389, 0.85506235],
       [0.54838539, 0.09715221, 0.83814813]])

In [24]:
np.random.seed(34) # in seed parameter can be any constant like it can be any integer
np.random.rand(5)

array([0.03856168, 0.78010046, 0.09270376, 0.63289269, 0.01389085])

In [31]:
np.random.seed(345)
100*np.random.rand(4,5)

array([[37.0926743 , 66.48842266, 49.66580045, 60.20790477, 24.41849444],
       [49.47480614, 71.05404148, 45.13923811,  4.70376596, 53.09777168],
       [55.30579044, 11.44349643, 24.54742428, 83.67018993, 90.57950611],
       [25.15657104, 20.26554019, 63.33126515,  2.40391447, 71.61133253]])

In [29]:
np.random.seed(3)
np.random.randint(low=-100,high=100,size=(3,2)) #we use randint where we have low,high exclude- so this gives numbers from -100 to 99 and the size


array([[   6,   52],
       [  31,   84],
       [-100,  -79]])

In [38]:
print(np.random.randn(5)) # random numbers from a (standard)normal distribution
print(np.random.randn(3,2)) #3*2 matrix of normally distributed random numbers.
np.random.randint(low=0,high=100,size=(5,2))

[ 0.69269143 -0.06268264  2.11894626 -1.74322237  1.46460693]
[[ 0.08580653 -1.43996055]
 [ 2.02195056  0.86952522]
 [ 0.39554566  1.16051486]]


array([[75, 86],
       [93, 72],
       [33, 68],
       [12, 29],
       [67, 24]])

#Array Operations

In [46]:
#Element-wise Operations
np.random.seed(3)
arr=np.random.rand(5)
print(arr)
arr=arr+1
arr=arr*2
arr

[0.5507979  0.70814782 0.29090474 0.51082761 0.89294695]


array([3.10159581, 3.41629565, 2.58180948, 3.02165521, 3.78589391])

In [58]:
#Element-wise Operations with Two Arrays of same size
arr1=np.zeros(5) #float [0. 0. 0. 0. 0.]
arr2=np.ones(5) #float [1. 1. 1. 1. 1.]
arr3=np.full(5,5) # integers [5 5 5 5 5]
arr1+=arr2
arr2*=arr3
# we get error if we choose arr3/=arr1 ->tries to put those floats back into the existing integer arr3.
arr3=(arr3/arr1).astype(int) #creates a new float array and assigns it to arr3, so it works.
print(arr3)
arr3=arr1/arr3
print(arr1)
print(arr2)
arr3






[5 5 5 5 5]
[1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5.]


array([0.2, 0.2, 0.2, 0.2, 0.2])

In [63]:
#Comparison Operations
arr=np.array([1,2,3,4,5])
greater_than_2=arr>2
print(greater_than_2)
#Selecting Elements Based on Conditions
selected_elements=arr[arr>1]
selected_elements
#summary Operations
print(arr.min()) #min value of all array elements
print(arr.max()) #max value of all array elements
print(arr.sum()) #sum of all elemnets in array
print(arr.mean()) #avg of all array elements
print(arr.std()) #standard deviation of all array elements

[False False  True  True  True]
1
5
15
3.0
1.4142135623730951
