<a href="https://colab.research.google.com/github/Narasimha0111/ml-ZoomCamp/blob/main/01-intro/01-intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print("Scikit-learn:", sklearn.__version__)

print("Environment ready!")

NumPy: 2.1.3
Pandas: 2.2.3
Scikit-learn: 1.6.1
Environment ready!


# 1.7 Introduction to NumPy


In [2]:
import numpy as np

#Creating array


In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.full(10,3.5)

array([3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5])

# List to array

In [11]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [14]:
a[2]

np.int64(3)

In [15]:
a[2]=10
a

array([ 1,  2, 10,  4,  5,  6])

Two more useful functions for creating arrays. arange creates a range of numbers - it works like the Python function range, except instead of an iterator it gives us a NumPy array. The last element is exclusive:

In [16]:
np.arange(3,11)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

##Multi-dimensional arrays

In [23]:
np.zeros((5,2)) #tuple shape , Uses mostly

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
np.zeros([5,2]) #list shape

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
n=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]]
         )

In [29]:
n[0][1]

np.int64(2)

In [30]:
n[0][1]=20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [31]:
n[2]

array([7, 8, 9])

In [32]:
n[2]=[2,2,2]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 2,  2,  2]])

In [33]:
n[:,2]

array([3, 6, 2])

In [34]:
n[:,2]=[0,1,2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 2,  2,  2]])

#Randomly generated arrays